package demo;

public class Exercise1211 {
	
	public static void main(String [] args)
	{
		/*2. Created one UITest class, created main method
	- created instance and added values using (setter and getter / constructor ) to that product and print those values
*/
		
		//code to display the assigned values in constructor
		Product P1 = new Product();
		System.out.println("---------Direct values from Constructor-----------");
		System.out.println(P1);
	
		//code to change the values that are default in constructor - only price value is changed
		
		//to clarify with mahesh how can i print both local and global value. how can i print both wholesale and retail price

		Product P2 = new Product();
		P2.setPrice(2); //setting the Retail price
		System.out.println("----Code to set the retail price - price value is changed locally------");
		System.out.println("Name is " + P2.getName());
		System.out.println("Description: " + P2.getDesc());
		System.out.println("Count is " + P2.getCount());
		System.out.println("Retail price is $"+ P2.getPrice());
		Product P3 = new Product(); //new object reference to print the wholesale price
		System.out.println("Wholesale price is $" + P3.getPrice());
		System.out.println("Company is " + Product.getCompany());
		
		//code to use the field constructor
		Product P4 = new Product("Ink pen", "This is an ink pen", 5, 3.2);
		System.out.println("---------Values displayed using field contructor--------");
		System.out.println (P4  + "company name is " + Product.getCompany() + "    Wholesale price is " + P1.getPrice());
	
		/*to clarify with Mahesh - this code is not working
		ProductService.ProductPrint(P1);*/
		
	}
	
	
}

/*3. Create ProductService class 
	- createProduct methods print product details using syso*/

class ProductService {
	
	public void ProductPrint (Product product)
	{
		System.out.println("---------Values displayed using Service class--------");
		System.out.println(product);
	}
}

/* 1. Create Product class and fields (name,desc,count,price) 
 default const, all arg const , setter and getter methods. */

class Product 
{
	private String name;
	private String desc;
	private int count;
	private double price; // wholesaleprice
	private static final String company = "Reynolds";
	
	/* autogenerated code for getter and setter methods*/
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDesc() {
		return desc;
	}
	public void setDesc(String desc) {
		this.desc = desc;
	}
	public int getCount() {
		return count;
	}
	public void setCount(int count) {
		this.count = count;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	public static String getCompany() {
		return company;
	}
	/*auto generated code for constructor with fieldnames/ variables*/
	public Product(String name, String desc, int count, double price) {
		super();
		this.name = name;
		this.desc = desc;
		this.count = count;
		this.price = price;
	}
	/*auto-generated and manually assigned values to variables*/
	public Product() {
		super();
		name = "ballpoint";
		desc = "This is a ball point pen";
		count = 10;
		price = 1.20;	
		// TODO Auto-generated constructor stub
		//ask Mahesh how to set different wholesale price to each product from constructor
	}
		
	
	//autogenerated tostring code
	@Override
//to be clarified with Mahesh - how to add constant variable to below code so it can be printed in the main class without writing any seperate code
	public String toString() {
		return "Product [name=" + name + ", desc=" + desc + ", count=" + count + ", price=" + price + "]";
	}
	}

/*
 *git clone https://github.com/maheshmarpudi11/core_java.git

under core_java folder
git status
git add . 
git status
git commit -m "Comment"
git push

 */
